name: Deploy Docker to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your entire repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Configure AWS credentials for EB
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # (Optional) You could run build/tests here if you like,
      # but EB will do 'docker build' on the server using Dockerfile.

      # 3) Create a zip of the entire repo,
      #    ignoring .git + .github for smaller size
      - name: Zip source code
        run: |
          zip -r deploy.zip . \
            -x ".git/*" \
            -x ".github/*"

      # 4) Deploy to Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}   # e.g. "MosefakApi"
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}   # e.g. "MosefakApi-env"
          version_label: "source-deploy-${{ github.sha }}"
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_deployment: true
